"""Initial migration

Revision ID: 90d39e006020
Revises: 
Create Date: 2026-08-31 11:10:32.978705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d39e006020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS inventory_parts CASCADE')
    op.drop_index(op.f('idx_time_value'), table_name='time_catalog')
    op.execute('DROP TABLE IF EXISTS time_catalog CASCADE')
    op.execute('DROP TABLE IF EXISTS company CASCADE')
    op.execute('DROP TABLE IF EXISTS windshield_catalog CASCADE')
    op.execute('DROP TABLE IF EXISTS windshield_catalog_vendor_prices CASCADE')
    op.execute('DROP TABLE IF EXISTS invoices CASCADE')
    op.execute('DROP TABLE IF EXISTS purchase_order_details CASCADE')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.execute('DROP TABLE IF EXISTS vendors CASCADE')
    op.drop_index(op.f('idx_customers_contact_phone2_numeric'), table_name='customers')
    op.drop_index(op.f('idx_customers_contact_phone_numeric'), table_name='customers')
    op.drop_index(op.f('idx_customers_name_trgm'), table_name='customers', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_customers_phone2_numeric'), table_name='customers')
    op.drop_index(op.f('idx_customers_phone_numeric'), table_name='customers')
    op.execute('DROP TABLE IF EXISTS customers CASCADE')
    op.execute('DROP TABLE IF EXISTS invoice_items CASCADE')
    op.execute('DROP TABLE IF EXISTS users CASCADE')
    op.drop_index(op.f('idx_invoice_payments_invoice_id'), table_name='invoice_payments')
    op.drop_index(op.f('idx_invoice_payments_status'), table_name='invoice_payments')
    op.execute('DROP TABLE IF EXISTS invoice_payments CASCADE')
    op.execute('DROP TABLE IF EXISTS vehicle_trims CASCADE')
    op.execute('DROP TABLE IF EXISTS vehicle_makes CASCADE')
    op.execute('DROP TABLE IF EXISTS purchase_order_receiving CASCADE')
    op.execute('DROP TABLE IF EXISTS estimate_details CASCADE')
    op.execute('DROP TABLE IF EXISTS purchase_orders CASCADE')
    op.execute('DROP TABLE IF EXISTS zipcodes CASCADE')
    op.drop_index(op.f('idx_concepts_is_active'), table_name='concepts')
    op.drop_index(op.f('idx_concepts_name'), table_name='concepts')
    op.drop_index(op.f('idx_concepts_sort_order'), table_name='concepts')
    op.execute('DROP TABLE IF EXISTS concepts CASCADE')
    op.execute('DROP TABLE IF EXISTS inventory_movements CASCADE')
    op.execute('DROP TABLE IF EXISTS vehicle_models CASCADE')
    op.drop_index(op.f('idx_estimates_address_date_type'), table_name='estimates')
    op.execute('DROP TABLE IF EXISTS estimates CASCADE')
    op.execute('DROP TABLE IF EXISTS vehicle_years CASCADE')
    op.execute('DROP TABLE IF EXISTS purchase_price_variances CASCADE')
    op.execute('DROP TABLE IF EXISTS estimates_history CASCADE')
    op.drop_index(op.f('idx_invoice_activities_concept_id'), table_name='invoice_activities')
    op.drop_index(op.f('idx_invoice_activities_created_at'), table_name='invoice_activities')
    op.drop_index(op.f('idx_invoice_activities_invoice_id'), table_name='invoice_activities')
    op.execute('DROP TABLE IF EXISTS invoice_activities CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('invoice_activities_concept_id_fkey')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_activities_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_activities_pkey'))
    )
    op.create_index(op.f('idx_invoice_activities_invoice_id'), 'invoice_activities', ['invoice_id'], unique=False)
    op.create_index(op.f('idx_invoice_activities_created_at'), 'invoice_activities', ['created_at'], unique=False)
    op.create_index(op.f('idx_invoice_activities_concept_id'), 'invoice_activities', ['concept_id'], unique=False)
    op.create_table('estimates_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('estimates_history_estimate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estimates_history_pkey'))
    )
    op.create_table('purchase_price_variances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('po_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('po_unit_cost', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('bill_unit_cost', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('variance', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_details.id'], name=op.f('purchase_price_variances_po_detail_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('purchase_price_variances_po_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_price_variances_pkey'))
    )
    op.create_table('vehicle_years',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_years_pkey')),
    sa.UniqueConstraint('year', name=op.f('vehicle_years_year_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('estimates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_vin', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('glass_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('window_position', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('date_request', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('estimated_appointment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estimated_appointment_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('operator_username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('authorized_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auth_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tax', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_method1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_amount1', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('payment_method2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_amount2', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=10), server_default=sa.text("'SHOP'::character varying"), autoincrement=False, nullable=False),
    sa.Column('customer_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mobile_fee_override', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('special_discount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('special_discount_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('alt_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alt_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('alt_contact_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('labor_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('materials_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('misc_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('void_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voided_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('voided_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duplication_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("glass_type::text = ANY (ARRAY['Windshield'::character varying, 'Side'::character varying, 'Rear'::character varying]::text[])", name=op.f('estimates_glass_type_check')),
    sa.CheckConstraint("language::text = ANY (ARRAY['English'::character varying, 'Spanish'::character varying, 'Mandarin'::character varying, 'Other'::character varying]::text[])", name=op.f('estimates_language_check')),
    sa.CheckConstraint("window_position::text = ANY (ARRAY['Front Driver'::character varying, 'Front Passenger'::character varying, 'Rear Driver'::character varying, 'Rear Passenger'::character varying, 'N/A'::character varying]::text[])", name=op.f('estimates_window_position_check')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('estimates_invoice_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_year_id'], ['vehicle_years.id'], name=op.f('estimates_vehicle_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('estimates_pkey'))
    )
    op.create_index(op.f('idx_estimates_address_date_type'), 'estimates', ['customer_address', 'estimated_appointment_date', 'service_type'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['vehicle_makes.id'], name=op.f('vehicle_models_make_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_models_pkey')),
    sa.UniqueConstraint('make_id', 'model', name=op.f('vehicle_models_make_id_model_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['inventory_parts.id'], name=op.f('inventory_movements_part_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_movements_pkey'))
    )
    op.create_table('concepts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('concepts_pkey')),
    sa.UniqueConstraint('name', name=op.f('concepts_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_concepts_sort_order'), 'concepts', ['sort_order'], unique=False)
    op.create_index(op.f('idx_concepts_name'), 'concepts', ['name'], unique=False)
    op.create_index(op.f('idx_concepts_is_active'), 'concepts', ['is_active'], unique=False)
    op.create_table('zipcodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('zipcodes_pkey'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('po_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('payment_terms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('vendor_invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shipping_handling', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('grand_total', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('purchase_orders_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_orders_pkey')),
    sa.UniqueConstraint('po_number', name=op.f('purchase_orders_po_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('estimate_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_taxable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('is_received', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('estimate_details_estimate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estimate_details_pkey'))
    )
    op.create_table('purchase_order_receiving',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_order_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_qty', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=20), server_default=sa.text("'OK'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_void', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('void_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_detail_id'], ['purchase_order_details.id'], name=op.f('purchase_order_receiving_purchase_order_detail_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('purchase_order_receiving_purchase_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_order_receiving_pkey'))
    )
    op.create_table('vehicle_makes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_makes_pkey')),
    sa.UniqueConstraint('make', name=op.f('vehicle_makes_make_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('vehicle_trims',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trim', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], name=op.f('vehicle_trims_model_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_trims_pkey')),
    sa.UniqueConstraint('model_id', 'trim', name=op.f('vehicle_trims_model_id_trim_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('invoice_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('deposited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deposited_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fee_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_payments_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_payments_pkey'))
    )
    op.create_index(op.f('idx_invoice_payments_status'), 'invoice_payments', ['payment_status'], unique=False)
    op.create_index(op.f('idx_invoice_payments_invoice_id'), 'invoice_payments', ['invoice_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('hire_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('is_taxable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('is_received', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_items_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_items_pkey'))
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contact_name2', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('contact_phone2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contact_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mood', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('allow_sms', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sms_opt_out_reason', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('referral_source', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('preferred_contact_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('credit_limit', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_tax_exempt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('tax_exempt_license', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('preferred_contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tax_exempt', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone_numeric', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone2_numeric', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contact_phone_numeric', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contact_phone2_numeric', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('idx_customers_phone_numeric'), 'customers', ['phone_numeric'], unique=False)
    op.create_index(op.f('idx_customers_phone2_numeric'), 'customers', ['phone2_numeric'], unique=False)
    op.create_index(op.f('idx_customers_name_trgm'), 'customers', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_customers_contact_phone_numeric'), 'customers', ['contact_phone_numeric'], unique=False)
    op.create_index(op.f('idx_customers_contact_phone2_numeric'), 'customers', ['contact_phone2_numeric'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('contact_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('terms_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vendors_pkey')),
    sa.UniqueConstraint('vendor_code', name=op.f('vendors_vendor_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('purchase_order_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity_ordered', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('line_subtotal', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('received_qty', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pending_qty', sa.NUMERIC(precision=12, scale=2), sa.Computed('(quantity_ordered - received_qty)', persisted=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('purchase_order_details_purchase_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_order_details_pkey'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_vin', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('glass_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('window_position', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('date_request', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_appointment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estimated_appointment_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('operator_username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('authorized_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auth_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Unpaid'::character varying"), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('tax', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_method1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_amount1', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('payment_method2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_amount2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), server_default=sa.text("'Unpaid'::character varying"), autoincrement=False, nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('customer_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mobile_fee_override', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('special_discount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('special_discount_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('alt_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alt_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('alt_contact_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('labor_cost', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('materials_cost', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('misc_cost', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('invoice_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('invoices_estimate_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_table('windshield_catalog_vendor_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('windshield_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('windshield_catalog_vendor_prices_vendor_id_fkey')),
    sa.ForeignKeyConstraint(['windshield_id'], ['windshield_catalog.id'], name=op.f('windshield_catalog_vendor_prices_windshield_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('windshield_catalog_vendor_prices_pkey')),
    sa.UniqueConstraint('windshield_id', 'vendor_id', name=op.f('windshield_catalog_vendor_prices_windshield_id_vendor_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('windshield_catalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nags_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('year_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trim_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehicle_makes.id'], name=op.f('windshield_catalog_make_id_fkey')),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], name=op.f('windshield_catalog_model_id_fkey')),
    sa.ForeignKeyConstraint(['trim_id'], ['vehicle_trims.id'], name=op.f('windshield_catalog_trim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('windshield_catalog_pkey')),
    sa.UniqueConstraint('nags_code', name=op.f('windshield_catalog_nags_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('business_line', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('main_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('main_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_notice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('registration_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('general_sales_tax', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('mobile_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('labor_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('materials_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('misc_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_table('time_catalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_value', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('display_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('time_catalog_pkey'))
    )
    op.create_index(op.f('idx_time_value'), 'time_catalog', ['time_value'], unique=False)
    op.create_table('inventory_parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('part_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity_on_hand', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('minimum_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('maximum_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('unit_sale', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_parts_pkey')),
    sa.UniqueConstraint('sku', name=op.f('inventory_parts_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###